CC = gcc
CFLAGS = -Og -g

all: simple_server server_select

simple_server: simple_server.c
	$(CC) $(CFLAGS) -o bin/simple_server simple_server.c

server_select: server_select.c
	$(CC) $(CFLAGS) -o bin/server_select server_select.c
