CC = gcc
CFLAGS = -Og -g

all: mystat myls

mystat: mystat.c
	$(CC) $(CFLAGS) -o bin/mystat mystat.c

myls: myls.c
	$(CC) $(CFLAGS) -o bin/myls myls.c

mytail: mytail.c
	$(CC) $(CFLAGS) -o bin/mytail mytail.c
