CC = gcc
CFLAGS = -Og -g

all: exercise1 exercise2 exercise3 exercise4 exercise5 exercise6 exercise7 exercise8

exercise1: exercise1.c
	$(CC) $(CFLAGS) -o bin/exercise1 exercise1.c

exercise2: exercise2.c
	$(CC) $(CFLAGS) -o bin/exercise2 exercise2.c

exercise3: exercise3.c
	$(CC) $(CFLAGS) -o bin/exercise3 exercise3.c

exercise4: exercise4.c
	$(CC) $(CFLAGS) -o bin/exercise4 exercise4.c

exercise5: exercise5.c
	$(CC) $(CFLAGS) -o bin/exercise5 exercise5.c

exercise6: exercise6.c
	$(CC) $(CFLAGS) -o bin/exercise6 exercise6.c

exercise7: exercise7.c
	$(CC) $(CFLAGS) -o bin/exercise7 exercise7.c

exercise8: exercise8.c
	$(CC) $(CFLAGS) -o bin/exercise8 exercise8.c
